# Generated by Django 6.0.3 on 2026-03-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_product2_orders"),
    ]

    operations = [
        migrations.AddField(
            model_name="product2",
            name="customer",
            field=models.ManyToManyField(
                blank=True, related_name="product2_customer", to="shop.customer"
            ),
        ),
    ]
